# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-04 14:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zip',
            old_name='country',
            new_name='county',
        ),
    ]
